# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Mathematical Modeling in Physics
author: Danny Caballero
logo: assets/images/logo.png
copyright: "2022"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: Mathematical_Modeling_in_Physics.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ./content/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/dannycab/phy415msu/  # Online location of your book
  path_to_book: MMIPbook  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# for references
sphinx:
  config:
    bibtex_reference_style: author_year
